---
- name: download mesos-dns
  get_url: url='{{mesos_dns_url}}' dest='/tmp/{{mesos_dns_app_gz}}'

- name: un-gz
  shell: gunzip -c '/tmp/{{mesos_dns_app_gz}}' > '{{installed_mesos_dns_app}}'
  args:
    creates: '{{installed_mesos_dns_app}}'

- name: chmod to executable
  file: path={{installed_mesos_dns_app}} mode=0755
    
- name: link
  file: >
    src='{{installed_mesos_dns_app}}'
    dest='{{mesos_dns_target_dir}}/mesos-dns'
    state=link

- name: create mesos-dns config directory
  file: >
    path={{mesos_dns_config_dir}}
    state=directory
    mode=0755
    owner=root
    group=root

- name: install config
  template: >-
    src='config.json.j2'
    dest='{{mesos_dns_config_json}}'
    mode=0644
    owner=root
    group=root
  
- name: install service
  template: >
    src='mesos-dns.service.j2'
    dest='/etc/systemd/system/mesos-dns.service'

- name: systemctl daemon-reload
  command: systemctl daemon-reload

- name: launch mesos-dns...
  service: name=mesos-dns.service enabled=yes state=started